name:                adventOfCode
version:             0.1.0.0
github:              "githubuser/adventOfCode"
license:             BSD3
author:              Christopher Grounds
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

description: Advent of code

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  advent:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -j +RTS -A128m -n2m -RTS
    dependencies:
    - adventOfCode
    - text

tests:
  adventOfCode-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventOfCode
    - hspec
